# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rentecaisse_development

test:
  <<: *default
  database: rentecaisse_test

production:
  <<: *default
  database: rentecaisse_production
  username: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
